// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace _2b2tAtlas.Server.Models;

public partial class AtlasContext : DbContext
{
    /// <summary>Initializes an Atlas unit of work with caller-configured SQLite options.</summary>
    /// <param name="options">EF Core options containing the database provider and connection configuration.</param>
    public AtlasContext(DbContextOptions<AtlasContext> options)
        : base(options)
    {
    }

    /// <summary>Gets or sets public HTTPS metadata links associated with Atlas locations.</summary>
    public virtual DbSet<Attachment> Attachments { get; set; }

    /// <summary>Gets or sets the public catalog of named Minecraft locations and native-dimension coordinates.</summary>
    public virtual DbSet<Location> Locations { get; set; }

    /// <summary>Gets or sets tile-pyramid renders anchored to individual Atlas locations.</summary>
    public virtual DbSet<Render> Renders { get; set; }

    /// <summary>Gets or sets authenticated Atlas accounts and their persisted security state.</summary>
    public virtual DbSet<User> Users { get; set; }

    /// <summary>Gets or sets historical and current warp names associated with locations.</summary>
    public virtual DbSet<Warp> Warps { get; set; }

    /// <inheritdoc/>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Attachment>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.LocationRow).WithMany(p => p.Attachments).OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.Property(e => e.Rowid).ValueGeneratedNever();
        });

        modelBuilder.Entity<Render>(entity =>
        {
            entity.HasOne(d => d.LocationRow).WithMany(p => p.Renders).OnDelete(DeleteBehavior.ClientSetNull);
            entity.HasOne(d => d.ArchiveWarp).WithOne(p => p.Render)
                .HasForeignKey<Render>(d => d.ArchiveWarpId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<Warp>(entity =>
        {
            entity.HasOne(d => d.LocationRow).WithMany(p => p.Warps).HasForeignKey(d => d.LocationRowid);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
