// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _2b2tAtlas.Server.Models;

/// <summary>
/// Persists one public HTTPS metadata link associated with an Atlas location.
/// </summary>
/// <remarks>This entity stores link metadata only; it never stores or accepts uploaded file bytes.</remarks>
[Index("LocationRowid", Name = "IX_Attachments_LocationRowid")]
public partial class Attachment
{
    /// <summary>Gets or sets the database identifier for the attachment link.</summary>
    [Key]
    public int Id { get; set; }

    /// <summary>Gets or sets the owning location's SQLite row identifier.</summary>
    public int LocationRowid { get; set; }

    /// <summary>Gets or sets the operator-supplied display label for the linked resource.</summary>
    [Required]
    public string FileName { get; set; }

    /// <summary>Gets or sets the normalized absolute HTTPS URL validated at the API trust boundary.</summary>
    [Required]
    public string FilePath { get; set; }

    /// <summary>Gets or sets the normalized media kind: Image, Video, Wiki, Link, Timeline, or Article.</summary>
    public string MediaType { get; set; }

    /// <summary>Gets or sets an optional lightweight HTTPS preview image.</summary>
    public string ThumbnailPath { get; set; }

    /// <summary>Gets or sets the original publication page retained for provenance.</summary>
    public string SourceUrl { get; set; }

    /// <summary>Gets or sets a concise public caption.</summary>
    public string Caption { get; set; }

    /// <summary>Gets or sets creator, archive, and license credit.</summary>
    public string Attribution { get; set; }

    /// <summary>Gets or sets the persisted UTC creation timestamp text.</summary>
    public string DateAddedUtc { get; set; }

    /// <summary>Gets or sets the required location navigation for this link.</summary>
    [ForeignKey("LocationRowid")]
    [InverseProperty("Attachments")]
    public virtual Location LocationRow { get; set; }
}
