// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _2b2tAtlas.Server.Models;

/// <summary>
/// Persists a named 2b2t location at exact native-dimension Minecraft block coordinates.
/// </summary>
/// <remarks>
/// Public API projections may include related warps, attachment links, and renders. The integer
/// primary key is a SQLite rowid alias generated by the database through the partial context mapping.
/// </remarks>
public partial class Location
{
    /// <summary>Database-generated SQLite row identifier.</summary>
    [Key]
    public int Rowid { get; set; }

    /// <summary>Stable cross-API UUID retained independently of the database rowid.</summary>
    [Required]
    public string LocationUuid { get; set; }

    /// <summary>Public name used in the Atlas directory and map.</summary>
    [Required]
    public string Name { get; set; }

    /// <summary>Gets or sets public historical or descriptive context for the location.</summary>
    public string Description { get; set; }

    /// <summary>Gets or sets legacy free-form classification text used by search and compatibility clients.</summary>
    public string Tags { get; set; }

    /// <summary>Optional public 2b2t wiki reference.</summary>
    public string Wiki { get; set; }

    /// <summary>Optional public video reference.</summary>
    public string VideoUrl { get; set; }

    /// <summary>Modern dimension code: 0 Overworld, 1 Nether, or 2 End.</summary>
    public int Dimension { get; set; }

    /// <summary>Native-dimension Minecraft block X coordinate.</summary>
    public int X { get; set; }

    /// <summary>Gets or sets the Minecraft block elevation.</summary>
    public int Y { get; set; }

    /// <summary>Native-dimension Minecraft block Z coordinate.</summary>
    public int Z { get; set; }

    /// <summary>Persisted UTC creation timestamp in round-trip text form.</summary>
    [Required]
    public string DateAddedUtc { get; set; }

    /// <summary>Gets or sets the UTC timestamp of the latest significant public-record change.</summary>
    [Required]
    public string ModifiedUtc { get; set; } = DateTime.UtcNow.ToString("o");

    /// <summary>Public HTTPS metadata links owned by this location.</summary>
    [InverseProperty("LocationRow")]
    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();

    /// <summary>Tile-pyramid captures anchored to this location.</summary>
    [InverseProperty("LocationRow")]
    public virtual ICollection<Render> Renders { get; set; } = new List<Render>();

    /// <summary>Gets or sets Archive teleport commands for historical WDLs of this location.</summary>
    [InverseProperty("LocationRow")]
    public virtual ICollection<Warp> Warps { get; set; } = new List<Warp>();

    /// <summary>Gets or sets explicit builder-group attributions for this location.</summary>
    public virtual ICollection<LocationGroup> LocationGroups { get; set; } = new List<LocationGroup>();
}
