// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _2b2tAtlas.Server.Models;

/// <summary>
/// Persists a tile-pyramid capture anchored to one Atlas location rather than a global dimension layer.
/// </summary>
/// <remarks>
/// Coordinate bounds use native-dimension block units and half-open maxima. Trusted ingestion
/// completion creates this row transactionally with its job state and, when needed, its location.
/// </remarks>
[Index("LocationRowid", Name = "IX_Renders_LocationRowid")]
[Index("ArchiveWarpId", Name = "IX_Renders_ArchiveWarpId", IsUnique = true)]
[Index("TilesPath", Name = "IX_Renders_TilesPath", IsUnique = true)]
public partial class Render
{
    /// <summary>Database-generated render identifier.</summary>
    [Key]
    public int Id { get; set; }

    /// <summary>Location row to which this capture is geographically anchored.</summary>
    public int LocationRowid { get; set; }

    /// <summary>Display name shown with the location's available captures.</summary>
    [Required]
    public string Name { get; set; }

    /// <summary>Gets or sets public provenance or rendering notes.</summary>
    public string Description { get; set; }

    /// <summary>Stable acquisition channel code for this render.</summary>
    public string Source { get; set; }

    /// <summary>One Archive warp whose WDL produced this render, when applicable.</summary>
    public int? ArchiveWarpId { get; set; }

    /// <summary>Modern dimension code: 0 Overworld, 1 Nether, or 2 End.</summary>
    public int Dimension { get; set; }

    /// <summary>Gets or sets the Atlas scale label describing the rendered footprint.</summary>
    [Required]
    public string Scale { get; set; }

    /// <summary>Unique public tile path registered by the trusted ingestion pipeline.</summary>
    [Required]
    public string TilesPath { get; set; }

    /// <summary>Whether the tile template exposes separate day and night pyramids.</summary>
    public int HasDayNight { get; set; }

    /// <summary>Gets or sets an optional public preview image path for directory presentation.</summary>
    public string PreviewImagePath { get; set; }

    /// <summary>Declared date of the source world download.</summary>
    public string WorldDownloadDate { get; set; }

    /// <summary>Inclusive minimum native-dimension block X bound.</summary>
    public int? MinX { get; set; }

    /// <summary>Inclusive minimum native-dimension block Z bound.</summary>
    public int? MinZ { get; set; }

    /// <summary>Exclusive maximum native-dimension block X bound.</summary>
    public int? MaxXExclusive { get; set; }

    /// <summary>Exclusive maximum native-dimension block Z bound.</summary>
    public int? MaxZExclusive { get; set; }

    /// <summary>Deepest generated XYZ zoom level before the client must upscale tiles.</summary>
    public int? MaxNativeZoom { get; set; }

    /// <summary>Registered coordinate-to-tile convention required to interpret the pyramid.</summary>
    public string CoordinateScheme { get; set; }

    /// <summary>
    /// Whether this capture is exposed by public map/catalog APIs. Equivalent collector
    /// captures remain stored and rerenderable while only their canonical representative is public.
    /// </summary>
    public int IsPublic { get; set; } = 1;

    /// <summary>Canonical public render represented by this equivalent capture.</summary>
    public int? EquivalentToRenderId { get; set; }

    /// <summary>Gets or sets the UTC registration timestamp in round-trip text form.</summary>
    [Required]
    public string DateAddedUtc { get; set; }

    /// <summary>Required location navigation for this capture.</summary>
    [ForeignKey("LocationRowid")]
    [InverseProperty("Renders")]
    public virtual Location LocationRow { get; set; }

    /// <summary>Exact Archive warp represented by this WDL render.</summary>
    [ForeignKey("ArchiveWarpId")]
    [InverseProperty("Render")]
    public virtual Warp ArchiveWarp { get; set; }
}
