// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace _2b2tAtlas.Server.Models;

public partial class User
{
    /// <summary>Gets or sets the database-generated account identifier used in JWT subject claims.</summary>
    [Key]
    public int Id { get; set; }

    /// <summary>Gets or sets the unique Atlas login and public display name.</summary>
    [Required]
    public string Username { get; set; } = null!;

    /// <summary>Gets or sets the unique Discord handle used as a login identity.</summary>
    public string? DiscordHandle { get; set; }

    /// <summary>Gets or sets the BCrypt credential digest; API projections must never expose this value.</summary>
    [Required]
    public string PasswordHash { get; set; } = null!;

    /// <summary>Gets or sets the canonical role identifier used to resolve effective permission claims.</summary>
    [Required]
    public string Role { get; set; } = null!;

    /// <summary>Gets or sets whether authentication is permitted, stored as 1 or 0.</summary>
    public int IsActive { get; set; }

    /// <summary>Gets or sets the legacy administrator compatibility flag, stored as 1 or 0 and derived from role assignment.</summary>
    public int IsAdmin { get; set; }

    /// <summary>Gets or sets the UTC account creation timestamp in round-trip text form.</summary>
    [Required]
    public string CreatedAt { get; set; } = null!;

    /// <summary>Gets or sets the most recent successful login UTC timestamp text.</summary>
    public string? LastLoginAt { get; set; }
}