using System.Text.RegularExpressions;
using SkiaSharp;

namespace _2b2tAtlas.Server.Services;

/// <summary>Composes the deepest tile level from a bounded unMINED web render into one PNG preview.</summary>
public static partial class RenderTileComposer
{
    /// <summary>A composed PNG and the exact block bounds represented by its cropped tile grid.</summary>
    public sealed record Result(
        byte[] Png,
        int Width,
        int Height,
        int MinX,
        int MinZ,
        int MaxXExclusive,
        int MaxZExclusive);

    [GeneratedRegex(@"^tile\.(-?\d+)\.(-?\d+)\.png$", RegexOptions.CultureInvariant)]
    private static partial Regex TileNamePattern();

    [GeneratedRegex(@"^zoom\.(\d+)$", RegexOptions.CultureInvariant)]
    private static partial Regex ZoomFolderPattern();

    /// <summary>Loads the deepest generated tile level and returns a tightly bounded PNG mosaic.</summary>
    /// <param name="renderRoot">The root directory generated by <c>unmined web render</c>.</param>
    /// <param name="cancellationToken">Token that cancels image loading or encoding.</param>
    /// <returns>The composed PNG bytes and dimensions.</returns>
    public static async Task<Result> ComposeAsync(
        string renderRoot,
        CancellationToken cancellationToken)
    {
        var zoomDirs = Directory.EnumerateDirectories(Path.Combine(renderRoot, "tiles"), "zoom.*")
            .Select(path => new { Path = path, Match = ZoomFolderPattern().Match(Path.GetFileName(path)) })
            .Where(item => item.Match.Success)
            .OrderBy(item => int.Parse(item.Match.Groups[1].Value))
            .ToList();

        foreach (var zoomDir in zoomDirs)
        {
            var tiles = Directory.EnumerateFiles(zoomDir.Path, "tile.*.*.png", SearchOption.AllDirectories)
                .Select(path => new { Path = path, Match = TileNamePattern().Match(Path.GetFileName(path)) })
                .Where(item => item.Match.Success)
                .Select(item => new
                {
                    item.Path,
                    X = int.Parse(item.Match.Groups[1].Value),
                    Y = int.Parse(item.Match.Groups[2].Value),
                })
                .ToList();
            if (tiles.Count == 0) continue;

            var minX = tiles.Min(tile => tile.X);
            var minY = tiles.Min(tile => tile.Y);
            var maxX = tiles.Max(tile => tile.X);
            var maxY = tiles.Max(tile => tile.Y);

            using var first = SKBitmap.Decode(tiles[0].Path)
                ?? throw new InvalidOperationException("A generated preview tile could not be decoded.");
            var tileWidth = first.Width;
            var tileHeight = first.Height;
            var width = (maxX - minX + 1) * tileWidth;
            var height = (maxY - minY + 1) * tileHeight;
            using var mosaic = new SKBitmap(width, height, SKColorType.Rgba8888, SKAlphaType.Premul);
            using var canvas = new SKCanvas(mosaic);
            canvas.Clear(SKColors.Transparent);

            foreach (var tile in tiles)
            {
                cancellationToken.ThrowIfCancellationRequested();
                using var image = SKBitmap.Decode(tile.Path)
                    ?? throw new InvalidOperationException($"Preview tile '{Path.GetFileName(tile.Path)}' could not be decoded.");
                var left = (tile.X - minX) * tileWidth;
                var top = (tile.Y - minY) * tileHeight;
                var destination = new SKRect(left, top, left + tileWidth, top + tileHeight);
                canvas.DrawBitmap(image, destination, new SKSamplingOptions(SKFilterMode.Nearest), null);
            }

            using var encoded = mosaic.Encode(SKEncodedImageFormat.Png, 100)
                ?? throw new InvalidOperationException("The composed preview could not be encoded as PNG.");
            var zoom = int.Parse(ZoomFolderPattern().Match(Path.GetFileName(zoomDir.Path)).Groups[1].Value);
            var blocksPerTile = checked(256 * (1 << zoom));
            return new Result(
                encoded.ToArray(),
                width,
                height,
                checked(minX * blocksPerTile),
                checked(minY * blocksPerTile),
                checked((maxX + 1) * blocksPerTile),
                checked((maxY + 1) * blocksPerTile));
        }

        throw new InvalidOperationException("The web render produced no PNG tiles.");
    }
}
